# The routes of the project.
#
# Each route describes how an incoming URL is going to be processed.

"http://{default}/":
    type: upstream
    upstream: "mymagento:http"

"http://{all}/":
    type: upstream
    upstream: "mymagento:http"

# Following routes configuration is needed to enable Application Server on Starter and Integration environments
#"http://{all}/graphql":
#    type: upstream
#    upstream: "application-server:http"
